# Generated by Django 3.1.6 on 2021-02-10 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Peliculas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.CharField(max_length=1000, verbose_name='Descripción')),
                ('year', models.DateField(verbose_name='Año de lanzamiento')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación en db')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de última actualización en db')),
            ],
            options={
                'verbose_name': 'Películas',
                'ordering': ['title', 'year'],
            },
        ),
        migrations.CreateModel(
            name='programacionSala',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha de presentación de película')),
                ('hour', models.TimeField(verbose_name='Hora de presentacion de película')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sala.peliculas', verbose_name='Película')),
            ],
        ),
    ]
