# Generated by Django 3.1.6 on 2021-02-22 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sala', '0006_auto_20210211_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='programacionsala',
            name='sala',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='sala.sala', verbose_name='Sala'),
        ),
    ]
