# Generated by Django 3.1.6 on 2021-02-22 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sala', '0007_programacionsala_sala'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programacionsala',
            name='sala',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sala.sala', verbose_name='Sala'),
        ),
    ]
