# Generated by Django 3.1.6 on 2021-02-11 13:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sala', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='peliculas',
            options={'ordering': ['-year', 'title'], 'verbose_name': 'Película', 'verbose_name_plural': 'Películas'},
        ),
        migrations.AddField(
            model_name='programacionsala',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de creación en db'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='programacionsala',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de última actualización en db'),
        ),
        migrations.AlterField(
            model_name='peliculas',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Nombre de la película'),
        ),
    ]
