# Generated by Django 3.1.6 on 2021-02-11 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sala', '0004_sala'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sala',
            name='number_chair',
            field=models.IntegerField(verbose_name='Número de Sillas'),
        ),
    ]
